openapi: 3.0.0
info:
  title: NodeJS Assessment API
  version: 1.0.0
paths:
  /server/incoming_data:
    post:
      summary: Receive incoming JSON and forward to destinations
      parameters:
        - in: header
          name: CL-X-TOKEN
          required: true
          schema:
            type: string
        - in: header
          name: CL-X-EVENT-ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Data received
